const TEST_ENV_API_KEY = 'testEnvApiKey'
const TEST_ENV_AWS_ACCESS_KEY = 'testEnvAwsAccessKey'
const TEST_ENV_AWS_SECRET_ACCESS_KEY = 'testEnvAwsAccessSecretKey'
const TEST_ENV_AWS_S3_BUCKET = 'testEnvAwsS3Bucket'

const TEST_API_KEY = 'testApiKey'
const TEST_AWS_ACCESS_KEY = 'testAwsAccessKey'
const TEST_AWS_SECRET_ACCESS_KEY = 'testAwsAccessSecretKey'
const TEST_AWS_S3_BUCKET = 'testAwsS3Bucket'

module.exports = {
  TEST_ENV_API_KEY: TEST_ENV_API_KEY,
  TEST_ENV_AWS_ACCESS_KEY: TEST_ENV_AWS_ACCESS_KEY,
  TEST_ENV_AWS_SECRET_ACCESS_KEY: TEST_ENV_AWS_SECRET_ACCESS_KEY,
  TEST_ENV_AWS_S3_BUCKET: TEST_ENV_AWS_S3_BUCKET,
  TEST_API_KEY: TEST_API_KEY,
  TEST_AWS_ACCESS_KEY: TEST_AWS_ACCESS_KEY,
  TEST_AWS_SECRET_ACCESS_KEY: TEST_AWS_SECRET_ACCESS_KEY,
  TEST_AWS_S3_BUCKET: TEST_AWS_S3_BUCKET
}
